# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('access_token', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='email_id',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Users'),
        ),
    ]
